### ISSUE TITLE
nixbuild hangs forever

### ISSUE THREAD

**Issue by KaiserKarel** [nixbuild/nixbuild-action#38]
I've added the CI workflow, however it hangs at `Run nixbuild/nixbuild-action@v16`

```
##[debug]Evaluating condition for step: 'Run nixbuild/nixbuild-action@v16'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run nixbuild/nixbuild-action@v16
##[debug]Register post job cleanup for action: nixbuild/nixbuild-action@v16
##[debug]Loading inputs
##[debug]Evaluating: secrets.nixbuild_ssh_key
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'nixbuild_ssh_key'
##[debug]=> '***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]'
##[debug]Result: '***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]'
##[debug]Evaluating: secrets.nixbuild_token
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'nixbuild_token'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: inputs.reuse-build-failures
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'reuse-build-failures'
##[debug]=> true
##[debug]Result: true
##[debug]Evaluating: inputs.reuse-build-timeouts
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'reuse-build-timeouts'
##[debug]=> false
##[debug]Result: false
##[debug]Loading env
Run nixbuild/nixbuild-action@v16
/home/runner/work/_actions/nixbuild/nixbuild-action/v16/nixbuild-action.sh {"NIXBUILD_SSH_KEY":"***\n","NIXBUILD_TOKEN":"","REUSE-BUILD-FAILURES":"true","REUSE-BUILD-TIMEOUTS":"false","GENERATE_SUMMARY_FOR":"","ALLOW-OVERRIDE":"","KEEP-BUILDS-RUNNING":""}
##[debug]Re-evaluate condition on job cancellation for step: 'Run nixbuild/nixbuild-action@v16'.
##[debug]NIXBUILD_SSH_KEY='***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***'
##[debug]NIXBUILD_TOKEN=''
Error: The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.NodeScriptActionHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Run nixbuild/nixbuild-action@v16
```

My yaml is as follows:

```yaml
name: Check

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  checks:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v16
    secrets:
      nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
    with:
      filter_builds: '.top_attr == "checks" or .top_attr == "packages" '
```

And my flake.nix is very simple:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-parts.url = "github:hercules-ci/flake-parts";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    ignite-cli-src = {
      flake = false;
      url = "github:ignite/cli/v0.26.1";      
    };

    swagger-combine-src = {
      flake = false;
      url = "github:maxdome/swagger-combine";
    };
  };
  outputs = inputs@{ self, nixpkgs, flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      systems =
        [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" "x86_64-darwin" ];
      perSystem = { config, self', inputs', pkgs, system, lib, ... }: rec {
        packages = {
          # ignite cli package for build/devshell
          swagger-combine = pkgs.buildNpmPackage {
            pname = "swagger-combine";
            version = "10.0.9";
            src = inputs.swagger-combine-src;
            dontNpmBuild = true;
            npmDepsHash = "sha256-FZR8hefkqTwSZJMX4lzS4zk7iGXi0+zi0ol1ia3iLYs=";
          };
          
          ignite-cli = pkgs.buildGoModule rec {
            allowGoReference = true;
            patches = [
              ./patches/protoc.patch
            ];
            nativeBuildInputs = [pkgs.protobuf];
            buildInputs = [pkgs.protobuf];
            name = "ignite-cli";
            src = inputs.ignite-cli-src;
            vendorSha256 = "sha256-4ajrp1UQ6mF75ZnZ69Y3QtRbsEsdDNm0J6pVZG+EwiY=";
            doCheck = false;
            ldflags = ''
              -X github.com/ignite/cli/ignite/version.Head=${src.rev}
              -X github.com/ignite/cli/ignite/version.Version=v0.26.1
              -X github.com/ignite/cli/ignite/version.Date=${builtins.toString (src.lastModified)}
            '';
          };
        };

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            self'.packages.ignite-cli
            protobuf
            nixfmt
            go
            gopls
            nodejs
          ];
          PROTOC="${pkgs.protobuf}/bin/protoc";
          SWAGGER_BIN="${self'.packages.swagger-combine}/bin/swagger-combine";
        };
        
        apps = {
          ignite-cli.program = "${config.packages.ignite-cli}/bin/ignite";
        };
      };
    };
}
```

**Comment by KaiserKarel** [comment]
Managed to fix it by switching to token-based authentication, making me think this is due to something going wrong with SSH keys.
